# Generated by Django 3.2.16 on 2022-11-17 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 17, 2, 55, 53, 3955)),
        ),
    ]
